name: Bug Tracker

on:
  issues:
    types: [opened]

env:
  MY_GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  assign_projects_and_notify:
    runs-on: ubuntu-latest
    name: Assign Projects and Notify
    steps:
      - name: Assign issues to projects
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/orgs/LUNAStudios/projects/1'
          column_name: 'Needs triage'

      - name: Send Discord webhook for bug reports
        uses: actions/checkout@v2
        
      - name: Run Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: node send-webhook.js
